# Generated by Django 3.2 on 2021-08-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_admin', '0002_alter_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
    ]
